apiVersion: v1
kind: Pod
metadata:
  name: gpu-operator-test-t4
spec:
  restartPolicy: OnFailure
  containers:
  - name: cuda-vector-add
    image: "nvidia/samples:vectoradd-cuda10.2"
    resources:
      limits:
         nvidia.com/gpu: 1
  nodeSelector: 
    nvidia.com/gpu.product: Tesla-T4